/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  darkMode: "class",
  theme: {
    colors: {
      base00: "hsl(var(--color-base00) / <alpha-value>)",
      base01: "hsl(var(--color-base01) / <alpha-value>)",
      base02: "hsl(var(--color-base02) / <alpha-value>)",
      base03: "hsl(var(--color-base03) / <alpha-value>)",
      base04: "hsl(var(--color-base04) / <alpha-value>)",
      base05: "hsl(var(--color-base05) / <alpha-value>)",
      base06: "hsl(var(--color-base06) / <alpha-value>)",
      base07: "hsl(var(--color-base07) / <alpha-value>)",
      base08: "hsl(var(--color-base08) / <alpha-value>)",
      base09: "hsl(var(--color-base09) / <alpha-value>)",
      base0A: "hsl(var(--color-base0A) / <alpha-value>)",
      base0B: "hsl(var(--color-base0B) / <alpha-value>)",
      base0C: "hsl(var(--color-base0C) / <alpha-value>)",
      base0D: "hsl(var(--color-base0D) / <alpha-value>)",
      base0E: "hsl(var(--color-base0E) / <alpha-value>)",
      base0F: "hsl(var(--color-base0F) / <alpha-value>)",

      bg: "hsl(var(--color-base02) / <alpha-value>)",
      "bg-alt": "hsl(var(--color-base01) / <alpha-value>)",
      text: "hsl(var(--color-base05) / <alpha-value>)",
      "text-inverted": "hsl(var(--color-base07) / <alpha-value>)",
      primary: "hsl(var(--color-base0C) / <alpha-value>)",
      accent: "hsl(var(--color-base0B) / <alpha-value>)",
      success: "hsl(var(--color-base0A) / <alpha-value>)",
      warning: "hsl(var(--color-base0E) / <alpha-value>)",
      danger: "hsl(var(--color-base0F) / <alpha-value>)",
      link: "hsl(var(--color-base0D) / <alpha-value>)",
      "link-hover": "hsl(var(--color-base0A) / <alpha-value>)",
      border: "hsl(var(--color-base03) / <alpha-value>)",
      muted: "hsl(var(--color-base04) / <alpha-value>)",
      code: "hsl(var(--color-base0E) / <alpha-value>)",
    },
    extend: {},
  },
  plugins: [],
};
